export const mockData = {
  user: {
    id: '1',
    name: 'Ahmet Yılmaz',
    email: 'ahmet@example.com',
    avatar: 'https://via.placeholder.com/100',
    city: 'İstanbul',
    district: 'Kadıköy',
    memberSince: '2023-01-15',
    points: 1250,
    level: 'Gold',
    complaintsSubmitted: 15,
    complaintsResolved: 12,
    photosShared: 28,
    likesReceived: 156,
  },
  
  cityServices: [
    { id: '1', name: 'Temizlik Hizmetleri', rating: 4.2, icon: 'cleaning-services' },
    { id: '2', name: 'Ulaşım', rating: 3.8, icon: 'directions-bus' },
    { id: '3', name: 'Park ve Bahçe', rating: 4.5, icon: 'park' },
    { id: '4', name: 'Su ve Kanalizasyon', rating: 3.9, icon: 'water-drop' },
    { id: '5', name: 'Çevre', rating: 4.1, icon: 'eco' },
  ],

  complaints: [
    {
      id: '1',
      title: 'Bozuk Kaldırım',
      description: 'Ana cadde üzerindeki kaldırım çok bozuk',
      category: 'Yol ve Kaldırım',
      status: 'Beklemede',
      date: '2024-08-15',
      location: { latitude: 41.0082, longitude: 28.9784 },
      photos: ['https://via.placeholder.com/200'],
      likes: 15,
      comments: 3,
    },
    {
      id: '2',
      title: 'Çöp Sorunu',
      description: 'Sokakta çöpler toplanmıyor',
      category: 'Temizlik',
      status: 'Çözüldü',
      date: '2024-08-14',
      location: { latitude: 41.0090, longitude: 28.9785 },
      photos: ['https://via.placeholder.com/200'],
      likes: 8,
      comments: 1,
    },
    {
      id: '3',
      title: 'Park Aydınlatması',
      description: 'Parkta lambalar çalışmıyor',
      category: 'Aydınlatma',
      status: 'İncelemede',
      date: '2024-08-13',
      location: { latitude: 41.0095, longitude: 28.9790 },
      photos: ['https://via.placeholder.com/200'],
      likes: 22,
      comments: 5,
    },
  ],

  institutions: [
    {
      id: '1',
      name: 'Kadıköy Belediyesi',
      rating: 4.3,
      phone: '+90 216 542 50 00',
      email: 'info@kadikoy.bel.tr',
      address: 'Osmanağa Mah. Söğütlüçeşme Cad. No:20',
      services: ['Temizlik', 'Ulaşım', 'Park ve Bahçe'],
      responseTime: '2-3 gün',
      resolutionRate: 85,
    },
    {
      id: '2',
      name: 'İSKİ',
      rating: 3.9,
      phone: '+90 444 1 ASKİ',
      email: 'info@iski.istanbul',
      address: 'Merkez Mah. Büyükdere Cad.',
      services: ['Su', 'Kanalizasyon'],
      responseTime: '1-2 gün',
      resolutionRate: 78,
    },
  ],

  achievements: [
    { id: '1', title: 'İlk Şikayet', description: 'İlk şikayetini gönderdin', icon: 'star', unlocked: true },
    { id: '2', title: 'Fotoğrafçı', description: '10 fotoğraf paylaştın', icon: 'camera', unlocked: true },
    { id: '3', title: 'Toplum Lideri', description: '50 beğeni aldın', icon: 'thumb-up', unlocked: false },
  ],

  recentActivity: [
    { id: '1', type: 'complaint', title: 'Yeni şikayet gönderildi', time: '2 saat önce' },
    { id: '2', type: 'photo', title: 'Fotoğraf paylaşıldı', time: '5 saat önce' },
    { id: '3', type: 'resolved', title: 'Şikayet çözüldü', time: '1 gün önce' },
  ],

  weather: {
    temperature: 28,
    condition: 'Güneşli',
    humidity: 65,
    windSpeed: 15,
    icon: 'sunny',
  },
};
